'\" t
.\" ** The above line should force tbl to be a preprocessor **
.\"
.\" Manual page for convertRTS
.\" to view the content formated, process with:
.\"     groff -man -Tlatin1 convertRTS.1 | less
.\" 
.\" Copyright (C), 2004 Guido Scholz
.\"
.\" You may distribute under the terms of the GNU General Public
.\" License as specified in the file COPYING that comes with the
.\" spdrs60 distribution.
.\"
.\" Sat Oct 03 11:33:52 CEST 2004  Guido Scholz <guido.scholz@bayernline.de>
.\"
.TH convertRTS 1 "03. Oct 2004" "Linux" "SRCP Clients"
.\"
.\"
.SH NAME
convertRTS \- konvertiert Fahrstraßendateien für spdrs60
.\"
.\"
.SH SYNTAX
.B convertRTS
.I datei
.\"
.\"
.SH BESCHREIBUNG
.B convertRTS
ist ein kleines Hilfsprogramm, das von
.I spdrs60
genutzt wird, um Fahrstraßendateien von einem älteren Format in das
aktuelle Format zu konvertieren.
.\"
.\"
.SH "SIEHE AUCH"
.BR spdrs60 (1),
.BR CentralClock (1)
.\"
.\"
.SH AUTOREN
.B convertRTS
wurde von Stefan Preis <info@linux-modellbahn.de> geschrieben.
Fehlerbereinigungen wurden von Guido Scholz <guido.scholz@bayernline.de>
beigetragen.
.PP
Diese Manualseite wurde von Guido Scholz erstellt.

