'\" t
.\" ** The above line should force tbl to be a preprocessor **
.\"
.\" Manual page for convertRTS
.\" to view the content formated, process with:
.\"     groff -man -Tlatin1 convertRTS.1 | less
.\" 
.\" Copyright (C), 2004 Guido Scholz
.\"
.\" You may distribute under the terms of the GNU General Public
.\" License as specified in the file COPYING that comes with the
.\" spdrs60 distribution.
.\"
.\" Sat Oct 03 10:33:52 CEST 2004  Guido Scholz <guido.scholz@bayernline.de>
.\"
.TH convertRTS 1 "03. Oct 2004" "Linux" "SRCP Clients"
.\"
.\"
.SH NAME
convertRTS \- convert routing files for spdrs60
.\"
.\"
.SH SYNOPSIS
.B convertRTS
.I file
.\"
.\"
.SH DESCRIPTION
.B convertRTS is a tool used by
.I spdrs60
to convert routing files from the old style format to the new format.
.\"
.\"
.SH "SEE ALSO"
.BR spdrs60 (1),
.BR CentralClock (1)
.\"
.\"
.SH AUTHORS
.B convertRTS
was written by Stefan Preis <info@linux-modellbahn.de> with
contributions Guido Scholz <guido.scholz@bayernline.de>.
.PP
This manual page was written by Guido Scholz.

