# Makefile.am for spdrs60
# Guido Scholz
# version: $Revision: 1.5 $
# last update: $Date: 2005-12-04 21:03:05 $

SUBDIRS = icons elements layouts \
        $(HTML_DOC) \
        man clock spdrs60


EXTRA_DIST = AUTHORS COPYING ChangeLog INSTALL README TODO NEWS \
	spdrs60.lsm \
	spdrs60.SuSE.desktop spdrs60.redhat.desktop \
	spdrs60.SuSE.spec spdrs60.redhat.spec

