# Makefile.am for spdrs60
# Guido Scholz
# version: $Revision: 1.6 $
# last update: $Date: 2005-12-06 16:51:39 $

SUBDIRS = icons elements layouts \
        $(HTML_DOC) \
        man clock spdrs60 debian


EXTRA_DIST = AUTHORS COPYING ChangeLog INSTALL README TODO NEWS \
	spdrs60.lsm \
	spdrs60.SuSE.desktop spdrs60.redhat.desktop \
	spdrs60.SuSE.spec spdrs60.redhat.spec

