# Makefile.am for spdrs60
# Guido Scholz
# version: $Revision: 1.11 $
# last update: $Date: 2009-10-26 21:59:43 $

SUBDIRS = icons layouts \
        doc man clock spdrs60


EXTRA_DIST = TODO \
	spdrs60.lsm qt3to4portingpatch.xml\
	spdrs60.SuSE.desktop spdrs60.redhat.desktop \
	spdrs60.SuSE.spec spdrs60.redhat.spec

