# Makefile.am with layout element icons

elementsdatadir = $(pkgdatadir)/elements

dist_elementsdata_DATA = adresse.xpm \
    blind.xpm diagonale_links_tl.xpm \
    diagonale_links.xpm diagonale_rechts_tl.xpm \
    diagonale_rechts.xpm dkw_links.xpm \
    dkw_rechts.xpm drehscheibe.xpm \
    dreier_weiche.xpm ekw_links.xpm \
    ekw_rechts.xpm entkoppler.xpm gerade_tl.xpm \
    gerade.xpm haus_1.xpm haus_2.xpm kreuzung_hose.xpm \
    kreuzung_links.xpm kreuzung_rechts.xpm \
    kurve_links.xpm kurve_rechts.xpm \
    LED_hp0.xpm LED_hp1.xpm LED_hp2.xpm \
    LED_mitte_gelb.xpm LED_mitte_rot.xpm LED_mitte_weiss.xpm \
    LED_oben_gelb.xpm LED_oben_rot.xpm LED_oben_weiss.xpm \
    LED_unten_gelb.xpm LED_unten_rot.xpm LED_unten_weiss.xpm \
    LED_sh1.xpm LED_vs0.xpm LED_vs1.xpm LED_vs2.xpm \
    leer.xpm motor_dc.xpm prellbock.xpm relais_1.xpm \
    relais.xpm richtung_1.xpm \
    richtung_2.xpm schiebebuehne.xpm \
    schuppen_m.xpm schuppen_o.xpm schuppen_u.xpm \
    signal_hss.xpm signal_hs.xpm signal_vs.xpm \
    signal_ss.xpm signal_ssh.xpm signal_sss.xpm \
    signal_ws_0.xpm signal_ws_1.xpm signal_ws.xpm \
    signal_zp.xpm \
    signal_nrb.xpm signal_srb.xpm \
    taste_fht.xpm taste_ufgt.xpm \
    taste_sgt.xpm taste_wgt.xpm \
    panel_blue.xpm panel_brown.xpm panel_yellow.xpm \
    panel_grey.xpm panel_green.xpm panel_red.xpm \
    uebergang.xpm weiche_y.xpm \
    weiche_diag_links.xpm weiche_diag_rechts.xpm \
    weiche_links.xpm weiche_rechts.xpm

