# Makefile.am for spdrs60 documentation
# last changes by: Guido Scholz
# Version: $Revision: 1.10 $
# last update: $Date: 2006-11-23 21:28:14 $

# HTML_DOC_DIR is defined in configure.ac
htmldir = @HTML_DOC_DIR@

enhtmldir = $(htmldir)/en
enimagesdir= $(enhtmldir)

dehtmldir = $(htmldir)/de
deimagesdir=$(dehtmldir)

commonimagesdir = $(htmldir)/commonimages

dist_enimages_DATA = \
	en/schnapp-bhf-klein.png \
	en/schnapp-daemoninfo.png \
	en/schnapp-daemonmenu.png \
	en/schnapp-deb-cmd2.png \
	en/schnapp-editctx.png \
	en/schnapp-editfilemenu.png \
	en/schnapp-editmenu.png \
	en/schnapp-feedbacks.png \
	en/schnapp-filemenu.png \
	en/schnapp-findnone.png \
	en/schnapp-find.png \
	en/schnapp-helpmenu.png \
	en/schnapp-historyfb.png \
	en/schnapp-historyinf.png \
	en/schnapp-history.png \
	en/schnapp-kdemenu.png \
	en/schnapp-keyboard.png \
	en/schnapp-layoutmenu.png \
	en/schnapp-mdc-comm.png \
	en/schnapp-menubar.png \
	en/schnapp-newlayout.png \
	en/schnapp-open.png \
	en/schnapp-pref-data-err1.png \
	en/schnapp-pref-data-err2.png \
	en/schnapp-pref-data.png \
	en/schnapp-pref-inter.png \
	en/schnapp-pref-layout-err1.png \
	en/schnapp-pref-layout.png \
	en/schnapp-pref-server-err1.png \
	en/schnapp-pref-server-err2.png \
	en/schnapp-prog-empty.png \
	en/schnapp-prop-adr.png \
	en/schnapp-prop-antrieb.png \
	en/schnapp-prop-dkw.png \
	en/schnapp-prop-dreh.png \
	en/schnapp-prop-entk.png \
	en/schnapp-prop-normal.png \
	en/schnapp-prop-signal-1.png \
	en/schnapp-prop-signal-2.png \
	en/schnapp-prop-signal-3.png \
	en/schnapp-route-adderror1.png \
	en/schnapp-route-adderror2.png \
	en/schnapp-route-add.png \
	en/schnapp-route-convert.png \
	en/schnapp-route-copy.png \
	en/schnapp-route-del.png \
	en/schnapp-route-rec1.png \
	en/schnapp-route-rec6.png \
	en/schnapp-route-saveerror.png \
	en/schnapp-routing-table2-all.png \
	en/schnapp-routing-table-all.png \
	en/schnapp-routing-table.png \
	en/schnapp-save.png \
	en/schnapp-sbn-comm.png \
	en/schnapp-tt-comm.png \
	en/schnapp-tt-comm-prog.png \
	en/schnapp-viewmenu.png


dist_deimages_DATA = \
	de/schnapp-bhf-klein.de.png \
	de/schnapp-daemoninfo.png \
	de/schnapp-daemonmenu.png \
	de/schnapp-deb-cmd2.png \
	de/schnapp-editctx.png \
	de/schnapp-editfilemenu.png \
	de/schnapp-editmenu.png \
	de/schnapp-feedbacks.png \
	de/schnapp-filemenu.png \
	de/schnapp-findnone.png \
	de/schnapp-find.png \
	de/schnapp-helpmenu.png \
	de/schnapp-historyfb.png \
	de/schnapp-historyinf.png \
	de/schnapp-history.png \
	de/schnapp-kdemenu.png \
	de/schnapp-keyboard.png \
	de/schnapp-layoutmenu.png \
	de/schnapp-mdc-comm.png \
	de/schnapp-menubar.png \
	de/schnapp-newlayout.png \
	de/schnapp-open.png \
	de/schnapp-pref-data-err1.png \
	de/schnapp-pref-data-err2.png \
	de/schnapp-pref-data.png \
	de/schnapp-pref-inter.png \
	de/schnapp-pref-layout-err1.png \
	de/schnapp-pref-layout.png \
	de/schnapp-pref-server-err1.png \
	de/schnapp-pref-server-err2.png \
	de/schnapp-prog-empty.de.png \
	de/schnapp-prop-adr.png \
	de/schnapp-prop-antrieb.png \
	de/schnapp-prop-dkw.png \
	de/schnapp-prop-dreh.png \
	de/schnapp-prop-entk.png \
	de/schnapp-prop-normal.png \
	de/schnapp-prop-signal-1.png \
	de/schnapp-prop-signal-2.png \
	de/schnapp-prop-signal-3.png \
	de/schnapp-route-adderror1.png \
	de/schnapp-route-adderror2.png \
	de/schnapp-route-add.png \
	de/schnapp-route-convert.png \
	de/schnapp-route-copy.png \
	de/schnapp-route-del.png \
	de/schnapp-route-rec1.png \
	de/schnapp-route-rec6.png \
	de/schnapp-route-saveerror.png \
        de/schnapp-routemenu.png \
	de/schnapp-routing-table2-all.png \
	de/schnapp-routing-table-all.png \
	de/schnapp-routing-table.png \
	de/schnapp-save.png \
	de/schnapp-sbn-comm.png \
	de/schnapp-tt-comm.png \
	de/schnapp-tt-comm-prog.png \
	de/schnapp-viewmenu.png


dist_commonimages_DATA = \
	commonimages/adresse.png \
	commonimages/blind-0.png \
	commonimages/blind-1.png \
	commonimages/dc-motor.jpg \
	commonimages/diagonale-links.png \
	commonimages/diagonale-links-tl.png \
	commonimages/diagonale-rechts.png \
	commonimages/diagonale-rechts-tl.png \
	commonimages/dkw-2state.png \
	commonimages/dkw-4state.png \
	commonimages/dkw-links-0.png \
	commonimages/dkw-links-1.png \
	commonimages/dkw-links-2.png \
	commonimages/dkw-links-3.png \
	commonimages/dkw-rechts-0.png \
	commonimages/dkw-rechts-1.png \
	commonimages/dkw-rechts-2.png \
	commonimages/dkw-rechts-3.png \
	commonimages/drehscheibe2.jpg \
	commonimages/drehscheibe.png \
	commonimages/dreier-weiche-0.png \
	commonimages/dreier-weiche-1.png \
	commonimages/dreier-weiche-2.png \
	commonimages/ekw-links-0.png \
	commonimages/ekw-links-1.png \
	commonimages/ekw-links-2.png \
	commonimages/ekw-rechts-0.png \
	commonimages/ekw-rechts-1.png \
	commonimages/ekw-rechts-2.png \
	commonimages/entkoppler-1.png \
	commonimages/entkoppler-2.png \
	commonimages/entkoppler-3.png \
	commonimages/entkoppler.png \
	commonimages/gerade.png \
	commonimages/gerade-tl.png \
	commonimages/haus-1.png \
	commonimages/haus-2.png \
	commonimages/kreuzung-hose.png \
	commonimages/kreuzung-links.png \
	commonimages/kreuzung-rechts.png \
	commonimages/kurve-links.png \
	commonimages/kurve-rechts.png \
	commonimages/leer.png \
	commonimages/prellbock.png \
	commonimages/relais.png \
	commonimages/richtung-1.png \
	commonimages/richtung-2.png \
	commonimages/schiebeb.jpg \
	commonimages/schiebebuehne.png \
	commonimages/schnapp-edit.png \
	commonimages/schnapp-feedbacks.png \
	commonimages/schnapp-found.png \
	commonimages/schnapp-route-pruef.png \
	commonimages/schnapp-route-rec2.png \
	commonimages/schnapp-route-rec3.png \
	commonimages/schnapp-route-rec4.png \
	commonimages/schnapp-route-rec5.png \
	commonimages/schnapp-routing-none.png \
	commonimages/schnapp-routing-occu.png \
	commonimages/schnapp-routing-show.png \
	commonimages/schnapp-toolbar.png \
	commonimages/schnapp-uhr.png \
	commonimages/schuppen-m.png \
	commonimages/schuppen-o.png \
	commonimages/schuppen-u.png \
	commonimages/signal-hs-0.png \
	commonimages/signal-hs-1.png \
	commonimages/signal-hs-2.png \
	commonimages/signal-hss-0.png \
	commonimages/signal-hss-1.png \
	commonimages/signal-hss-2.png \
	commonimages/signal-hss-3.png \
	commonimages/signal-nrb.png \
	commonimages/signal-srb.png \
	commonimages/signal-ssh-0.png \
	commonimages/signal-sss-0.png \
	commonimages/signal-ss-0.png \
	commonimages/signal-ss-1.png \
	commonimages/signal-vs-0.png \
	commonimages/signal-vs-1.png \
	commonimages/signal-vs-2.png \
	commonimages/signal-ws-0.png \
	commonimages/signal-ws-1.png \
	commonimages/signal-zf-0.png \
	commonimages/signal-zf-1.png \
	commonimages/taste-fht.png \
	commonimages/taste-wgt.png \
	commonimages/taste-sgt.png \
	commonimages/taste-ufgt.png \
	commonimages/panel-blue.png \
	commonimages/uebergang.png \
	commonimages/weiche-diag-links-0.png \
	commonimages/weiche-diag-links-1.png \
	commonimages/weiche-diag-rechts-0.png \
	commonimages/weiche-diag-rechts-1.png \
	commonimages/weiche-links-0.png \
	commonimages/weiche-links-1.png \
	commonimages/weiche-rechts-0.png \
	commonimages/weiche-rechts-1.png
        
dist_html_DATA = spdrs60.css 

# enHTMLFILES =
enhtml_DATA = \
	en/index.html \
	en/sect-changes.html \
	en/sect-connections.html \
	en/sect-faq.html \
	en/sect-feedback.html \
	en/sect-install.html \
	en/sect-introduction.html \
	en/sect-misc.html \
	en/sect-routes.html \
	en/sect-symbols.html \
	en/sect-usage.html
	
#deHTMLFILES = 
dehtml_DATA = \
	de/index.html \
        de/sect-aenderungen.html \
        de/sect-anschluesse.html \
        de/sect-bedienung.html \
        de/sect-einfuehrung.html \
        de/sect-fahrstrassen-allg.html \
        de/sect-faq.html \
        de/sect-installation.html \
        de/sect-rueckmeldung.html \
        de/sect-sonstiges.html \
        de/sect-symbole.html


CLEANFILES = \
	$(enhtml_DATA) $(dehtml_DATA)

# distributed with package but not installed
EXTRA_DIST = en/index.sgml de/index.sgml \
    spdrs60.dsl jadetex.cfg


#SUFFIXES= .png .jpg .eps #.sgml .html .ps .pdf

#.png.eps:
#	convert $< eps2:$@

#.jpg.eps:
#	convert $< eps2:$@

# Sprache aus den ersten zwei Zeichen von "Target" ermitteln, 
# entsprechend den Unterverzeichnissen der sgml-Dateien

en/index.html: en/index.sgml $(dist_commonimages_DATA) $(dist_enimages_DATA) spdrs60.dsl
	cd en; $(JADE) -b ISO-8859-1 -t sgml -i html -d "../spdrs60.dsl#html" index.sgml; cd ..

#en/index.tex: en/index.sgml $(dist_commonimages_DATA) $(dist_enimages_DATA) spdrs60.dsl
#	cd en; $(JADE) -b ISO-8859-1 -t tex -d "../spdrs60.dsl#print" index.sgml; cd ..

de/index.html: de/index.sgml $(dist_commonimages_DATA) $(dist_deimages_DATA) spdrs60.dsl
	cd de; $(JADE) -b ISO-8859-1 -t sgml -i html -d "../spdrs60.dsl#html" index.sgml; cd ..

#de/index.tex: de/index.sgml $(dist_commonimages_DATA) $(dist_deimages_DATA) spdrs60.dsl
#	cd de; $(JADE) -b ISO-8859-1 -t tex -d "../spdrs60.dsl#print" index.sgml; cd ..


