# Makefile.am for spdrs60 documentation
# last changes by: Guido Scholz
# Version: $Revision: 1.23 $
# last update: $Date: 2008-06-17 19:02:05 $

# HTML_DOC_DIR is defined in configure.ac
htmldir = @HTML_DOC_DIR@

enhtmldir = $(htmldir)/en
enimagesdir= $(enhtmldir)

dehtmldir = $(htmldir)/de
deimagesdir=$(dehtmldir)

commonimagesdir = $(htmldir)/commonimages

dist_enimages_DATA = \
	en/schnapp-routing-table2-all.png \
	en/schnapp-routing-table-all.png


dist_deimages_DATA = \
	de/schnapp-bhf-klein.png \
	de/schnapp-daemoninfo.png \
	de/schnapp-daemonmenu.png \
	de/schnapp-deb-cmd2.png \
	de/schnapp-editfilemenu.png \
	de/schnapp-editmenu.png \
	de/schnapp-feedbacks.png \
	de/schnapp-filemenu.png \
	de/schnapp-find.png \
	de/schnapp-helpmenu.png \
	de/schnapp-hints.png \
	de/schnapp-historyhints.png \
	de/schnapp-historyinf.png \
	de/schnapp-history.png \
	de/schnapp-kdemenu.png \
	de/schnapp-keyboard.png \
	de/schnapp-layoutmenu.png \
	de/schnapp-mdc-comm.png \
	de/schnapp-menubar.png \
	de/schnapp-newlayout.png \
	de/schnapp-open.png \
	de/schnapp-pref-data.png \
	de/schnapp-pref-layout.png \
	de/schnapp-prog-empty.png \
	de/schnapp-prop-adr.png \
	de/schnapp-prop-antrieb.png \
	de/schnapp-prop-dkw.png \
	de/schnapp-prop-dreh.png \
	de/schnapp-prop-entk.png \
	de/schnapp-prop-normal.png \
	de/schnapp-prop-signal-1.png \
	de/schnapp-prop-signal-2.png \
	de/schnapp-route-adderror1.png \
	de/schnapp-route-add.png \
	de/schnapp-route-rec1.png \
	de/schnapp-route-rec6.png \
        de/schnapp-routemenu.png \
	de/schnapp-routing-table.png \
	de/schnapp-save.png \
	de/schnapp-sbn-comm.png \
	de/schnapp-tt-comm.png \
	de/schnapp-tt-comm-prog.png \
	de/schnapp-viewmenu.png \
	de/shot-paintitemtoolbox.png \
	de/shot-pref-elements.png \
	de/shot-pref-feedback.png \
	de/shot-pref-feedbacktype.png \
	de/shot-routedialog1.png \
	de/shot-routedialog2.png \
	de/shot-routedialog3.png \
	de/shot-routedialog4.png \
	de/shot-trainnumberdialog.png \
	de/shot-trainnumber-display2.png


dist_commonimages_DATA = \
	commonimages/adresse.png \
	commonimages/blind-0.png \
	commonimages/blind-1.png \
	commonimages/dc-motor.jpg \
	commonimages/diagonale-links.png \
	commonimages/diagonale-links-tl.png \
	commonimages/diagonale-rechts.png \
	commonimages/diagonale-rechts-tl.png \
	commonimages/dkw-2state.png \
	commonimages/dkw-4state.png \
	commonimages/dkw-links-0.png \
	commonimages/dkw-links-1.png \
	commonimages/dkw-links-2.png \
	commonimages/dkw-links-3.png \
	commonimages/dkw-rechts-0.png \
	commonimages/dkw-rechts-1.png \
	commonimages/dkw-rechts-2.png \
	commonimages/dkw-rechts-3.png \
	commonimages/drehscheibe2.jpg \
	commonimages/drehscheibe.png \
	commonimages/dreier-weiche-0.png \
	commonimages/dreier-weiche-1.png \
	commonimages/dreier-weiche-2.png \
	commonimages/ekw-links-0.png \
	commonimages/ekw-links-1.png \
	commonimages/ekw-links-2.png \
	commonimages/ekw-rechts-0.png \
	commonimages/ekw-rechts-1.png \
	commonimages/ekw-rechts-2.png \
	commonimages/entkoppler-1.png \
	commonimages/entkoppler-2.png \
	commonimages/entkoppler-3.png \
	commonimages/entkoppler.png \
	commonimages/gerade.png \
	commonimages/gerade-tl.png \
	commonimages/haus-1.png \
	commonimages/haus-2.png \
	commonimages/kreuzung-hose.png \
	commonimages/kreuzung-links.png \
	commonimages/kreuzung-rechts.png \
	commonimages/kurve-links.png \
	commonimages/kurve-rechts.png \
	commonimages/leer.png \
	commonimages/motor.png \
	commonimages/prellbock.png \
	commonimages/relais.png \
	commonimages/richtung-1.png \
	commonimages/richtung-2.png \
	commonimages/schiebeb.jpg \
	commonimages/schiebebuehne.png \
	commonimages/schnapp-edit.png \
	commonimages/schnapp-feedbacks.png \
	commonimages/schnapp-found.png \
	commonimages/schnapp-route-pruef.png \
	commonimages/schnapp-route-rec2.png \
	commonimages/schnapp-route-rec3.png \
	commonimages/schnapp-route-rec4.png \
	commonimages/schnapp-route-rec5.png \
	commonimages/schnapp-routing-none.png \
	commonimages/schnapp-routing-occu.png \
	commonimages/schnapp-routing-show.png \
	commonimages/schnapp-toolbar.png \
	commonimages/schnapp-uhr.png \
	commonimages/schuppen-m.png \
	commonimages/schuppen-o.png \
	commonimages/schuppen-u.png \
	commonimages/signal-hs-0.png \
	commonimages/signal-hs-1.png \
	commonimages/signal-hs-2.png \
	commonimages/signal-hss-0.png \
	commonimages/signal-hss-1.png \
	commonimages/signal-hss-2.png \
	commonimages/signal-hss-3.png \
	commonimages/signal-nrb.png \
	commonimages/signal-srb.png \
	commonimages/signal-ssh-0.png \
	commonimages/signal-sss-0.png \
	commonimages/signal-ss-0.png \
	commonimages/signal-ss-1.png \
	commonimages/signal-vs-0.png \
	commonimages/signal-vs-1.png \
	commonimages/signal-vs-2.png \
	commonimages/signal-ws-0.png \
	commonimages/signal-ws-1.png \
	commonimages/signal-zf-0.png \
	commonimages/signal-zf-1.png \
	commonimages/switch-y-0.png \
	commonimages/switch-y-1.png \
	commonimages/taste-fht.png \
	commonimages/taste-wgt.png \
	commonimages/taste-sgt.png \
	commonimages/taste-ufgt.png \
	commonimages/trackvertical.png \
	commonimages/shot-trainnumber-display1.png \
	commonimages/shot-trainnumber-display3.png \
	commonimages/turn_botvert_left.png \
	commonimages/turn_botvert_right.png \
	commonimages/turn_topvert_left.png \
	commonimages/turn_topvert_right.png \
	commonimages/panel-blue.png \
	commonimages/uebergang.png \
	commonimages/weiche-diag-links-0.png \
	commonimages/weiche-diag-links-1.png \
	commonimages/weiche-diag-rechts-0.png \
	commonimages/weiche-diag-rechts-1.png \
	commonimages/weiche-links-0.png \
	commonimages/weiche-links-1.png \
	commonimages/weiche-rechts-0.png \
	commonimages/weiche-rechts-1.png


dist_html_DATA = spdrs60.css 


if HTML_DOC
enhtml_DATA = \
	en/index.html \
	en/sect-changes.html \
	en/sect-connections.html \
	en/sect-faq.html \
	en/sect-feedback.html \
	en/sect-install.html \
	en/sect-introduction.html \
	en/sect-misc.html \
	en/sect-routes.html \
	en/sect-symbols.html \
	en/sect-usage.html
else
enhtml_DATA =
endif

if HTML_DOC
dehtml_DATA = \
	de/index.html \
	de/chapter-aenderungen.html \
	de/chapter-anschluesse.html \
	de/chapter-bedienung.html \
	de/chapter-einfuehrung.html \
	de/chapter-fahrstrassen-allg.html \
	de/chapter-faq.html \
	de/chapter-installation.html \
	de/chapter-rueckmeldung.html \
	de/chapter-sonstiges.html \
	de/chapter-standardnachrichten.html \
	de/chapter-symbole.html \
	de/sect-anschluesse-weichen.html \
	de/sect-bedienelemente.html \
	de/sect-bezugsquellen.html \
	de/sect-bugs.html \
        de/sect-crcf-datenabfrage.html \
        de/sect-crcf-dateneinstellung.html \
        de/sect-crcf-rundruf.html \
	de/sect-copyright.html \
	de/sect-gm-allgemein.html \
	de/sect-gm-anwendung.html \
	de/sect-gm-crcf.html \
	de/sect-dateien.html \
	de/sect-drehscheibe.html \
	de/sect-elementstellungen.html \
	de/sect-erzeugen.html \
	de/sect-fahrstrassen-bedienung.html \
	de/sect-fahrstrassen.html \
	de/sect-fahrstrassen-vorwort.html \
	de/sect-filestructure.html \
	de/sect-gleichstrommotoren.html \
	de/sect-grundlegende-bedienung.html \
	de/sect-installieren.html \
	de/sect-kompilieren.html \
	de/sect-layout-ladenspeichern.html \
	de/sect-literatur.html \
	de/sect-menuepunkte.html \
	de/sect-optionen.html \
	de/sect-schiebebuehne.html \
	de/sect-signale.html \
	de/sect-starten.html \
	de/sect-symboleedit.html \
	de/sect-symboleigenschaften.html \
	de/sect-symbole-uebersicht.html \
	de/sect-tastaturkuerzel.html \
        de/sect-trainnumber-introduction.html \
	de/sect-trainnumber-usage.html \
	de/sect-voraussetzungen.html \
	de/v0.2.1.html \
	de/v0.2.html \
	de/v0.3.1.html \
	de/v0.3.2.html \
	de/v0.3.3.html \
	de/v0.3.4.html \
	de/v0.3.html \
	de/v0.4.0.html \
	de/v0.4.1.html \
	de/v0.4.2.html \
	de/v0.4.3.html \
	de/v0.4.3-qt3.html \
	de/ver-0.4.4.html \
	de/ver-0.4.5.html \
	de/ver-0.4.6.html \
	de/ver-0.4.7.html \
	de/ver-0.4.8.html \
	de/ver-0.5.0.html \
	de/ver-0.5.1.html \
	de/ver-0.5.2.html \
	de/ver-0.5.3.html

else
dehtml_DATA =
endif

tex_files = \
    de/index.tex de/index.dvi de/index.out de/index.log \
    de/index.aux de/index.pdf

CLEANFILES = \
	$(enhtml_DATA) $(dehtml_DATA) $(tex_files)

# distributed with package but not installed
EXTRA_DIST = en/index.sgml de/index.sgml \
    spdrs60.dsl jadetex.cfg


#SUFFIXES= .png .jpg .eps #.sgml .html .ps .pdf

#.png.eps:
#	convert $< eps2:$@

#.jpg.eps:
#	convert $< eps2:$@

# Sprache aus den ersten zwei Zeichen von "Target" ermitteln, 
# entsprechend den Unterverzeichnissen der sgml-Dateien

# use jade rules only if html documentation is enabled
if HTML_DOC

en/index.html: en/index.sgml $(dist_commonimages_DATA) $(dist_enimages_DATA) spdrs60.dsl
	cd en; $(JADE) -b ISO-8859-1 -t sgml -i html -d "../spdrs60.dsl#html" index.sgml; cd ..

#en/index.tex: en/index.sgml $(dist_commonimages_DATA) $(dist_enimages_DATA) spdrs60.dsl
#	cd en; $(JADE) -b ISO-8859-1 -t tex -d "../spdrs60.dsl#print" index.sgml; cd ..

de/index.html: de/index.sgml $(dist_commonimages_DATA) $(dist_deimages_DATA) spdrs60.dsl
	cd de; $(JADE) -b ISO-8859-1 -t sgml -i html -d "../spdrs60.dsl#html" index.sgml; cd ..

de/index.tex: de/index.sgml $(dist_commonimages_DATA) $(dist_deimages_DATA) spdrs60.dsl
	cd de; $(JADE) -b ISO-8859-1 -t tex -d "../spdrs60.dsl#print" index.sgml; cd ..

# this is not complete, just a shortcut to generate a pdf handbook
pdf: de/index.tex
	cd de; pdfjadetex index.tex; cd ..
endif
