# Makefile.am for spdrs60, pixmaps included by cpp-files
# (c) Guido Scholz
# version: $Revision: 1.5 $
# last update: $Date: 2005-11-09 21:05:14 $

EXTRA_DIST = filenew.xpm filesave.xpm fileopen.xpm \
    fileclose.xpm fileimport.xpm filenewwindow.xpm \
    filequit.xpm filesaveas.xpm \
    editcut.xpm editcopy.xpm editpaste.xpm \
    editfind.xpm editoptions.xpm \
    viewroute.xpm viewfeedback.xpm viewkeyboard.xpm \
    viewclock.xpm route_locked.xpm route_unlocked.xpm\
    viewlayouteditmode.xpm viewnormalmode.xpm viewrouteeditmode.xpm \
    daemonconnect.xpm daemondisconnect.xpm \
    daemoninfo.xpm daemonkill.xpm daemonreset.xpm \
    layoutstart.xpm layoutstop.xpm layoutnotrot.xpm \
    route_clear.xpm route_copy.xpm route_edit.xpm \
    route_new.xpm route_record.xpm route_start.xpm \
    route_stop.xpm route_view.xpm route_editmode.xpm \
    route_apply.xpm \
    cursor_fht_b.xpm cursor_fht_m.xpm \
    cursor_wgt_b.xpm cursor_wgt_m.xpm \
    cursor_mgt_b.xpm cursor_mgt_m.xpm \
    cursor_ufgt_b.xpm cursor_ufgt_m.xpm \
    cursor_sgt_b.xpm cursor_sgt_m.xpm \
    cursor_hagt_b.xpm cursor_hagt_m.xpm \
    cursor_rzs_b.xpm cursor_rzs_m.xpm \
    cursor_uzs_b.xpm cursor_uzs_m.xpm \
    cursor_zhs_b.xpm cursor_zhs_m.xpm \
    cursor_rrs_b.xpm cursor_rrs_m.xpm \
    cursor_urs_b.xpm cursor_urs_m.xpm \
    tt_goto.xpm tt_left_step.xpm tt_left.xpm tt_prog.xpm \
    tt_right_step.xpm tt_right.xpm tt_stop.xpm tt_turn180.xpm \
    fb_nextpage.xpm fb_prevpage.xpm fb_s44.xpm fb_s88.xpm \
    ctx_clear.xpm ctx_l_curve.xpm ctx_l_diag.xpm ctx_l_turn.xpm \
    ctx_r_curve.xpm ctx_r_diag.xpm ctx_rota.xpm ctx_r_turn.xpm \
    ctx_straight.xpm entkoppler_st1.xpm entkoppler_st2.xpm \
    entkoppler_st3.xpm dkw_links_st2.xpm dkw_links_st3.xpm \
    dkw_rechts_st2.xpm dkw_rechts_st3.xpm \
    signal_hss_st1.xpm signal_hss_st2.xpm signal_hss_st3.xpm \
    signal_hs_st1.xpm signal_hs_st2.xpm signal_hs_st3.xpm \
    signal_vs_st1.xpm signal_vs_st2.xpm signal_vs_st3.xpm \
    elemcom_down.xpm elemcom_up.xpm \
    drehscheibe_st2.xpm drehscheibe_st3.xpm tt_tracks.xpm

