layoutdatadir = $(pkgdatadir)/layouts

layoutdata_DATA = alle_elemente.dat.gbs \
                  bahnhof_gross.dat.gbs bahnhof_gross.dat.rts \
                  bahnhof_klein.dat.gbs bahnhof_klein.dat.rts \
                  KleinMaschen.dat.gbs  KleinMaschen.dat.rts \
                  reststeinzeit.dat.gbs search_example.dat.gbs \
                  dedorf.dat.gbs dedorf.dat.rts \
                  Lintorf.dat.gbs Lintorf.dat.rts \
                  Flandersbach.dat.gbs Flandersbach.dat.rts

EXTRA_DIST = $(layoutdata_DATA)
