# Makefile.am for spdrs60
# Guido Scholz
# version: $Revision: 1.3 $
# last update: $Date: 2008-08-08 17:10:41 $

layoutdatadir = $(pkgdatadir)/layouts

dist_layoutdata_DATA = \
	abzw-bf.spdrs60 \
	alle_elemente.spdrs60 \
	bahnhof_gross.spdrs60 \
	bahnhof_klein.spdrs60 \
	dedorf.spdrs60 \
	flandersbach.spdrs60 \
	kleinmaschen.spdrs60 \
	lintorf.spdrs60

